### ISSUE TITLE
Enhancement for the denomination quantity and amount tally

### ISSUE THREAD

**Issue by luchj1125** [KimiQianMin/vmcs_se22_pt04_u7#1]
To provide an at-a-glance display of this cash amount available, by denomination, for collection by the Maintainer, this will enable the Maintainer to readily tally the total cash collected and the total number of coins by denomination displayed in "show total cash held" and "Press to collect cash" when pressed, thus leaving no room for dispute over system errors.

Technical lead, please update Design model report before developer start development

**Comment by pengjianemgmail** [comment]
I have updated design report

**Comment by luchj1125** [comment]
Thanks PJ.

Hi Aung, please follow up design report to do your development.

**Comment by myatmyoaung** [comment]
I have done the enhancement and checked in, please verify

**Comment by luchj1125** [comment]
Hi Xy, we have completed enhancement, please verify

**Comment by kirivarnan** [comment]
I have worked with user xysim1, test has been done

**Comment by xysim1** [comment]
verified, please prepare for release

**Comment by luchj1125** [comment]
Kimi, please prepare for release, thanks

**Comment by KimiQianMin** [comment]
Release doc has been approved and released

**Comment by luchj1125** [comment]
Thanks, please create a tag for recent changes
