### ISSUE TITLE
Defect for reset the values to null after session out

### ISSUE THREAD

**Issue by luchj1125** [KimiQianMin/vmcs_se22_pt04_u7#2]
Reset the values to null for "Show Total Cash Held" and "Press to Collect Cash" when the Maintainer successfully pushes "Press Here When Finished".

Technical lead, please update the design report before developer start implementation.

**Comment by pengjianemgmail** [comment]
I have updated design report

**Comment by luchj1125** [comment]
Thanks PJ.

Hi Aung, please start your development, this is the highest priority.

**Comment by myatmyoaung** [comment]
I have committed by updated source code to repository, please verify

**Comment by luchj1125** [comment]
Hi XY, my developer has fixed this defect, please verify

**Comment by xysim1** [comment]
Dear Project Manager,

The verification has been done, please prepare for release, thanks

**Comment by kirivarnan** [comment]
Yes, I have worked with user xysim1, done this testing, please prepare for release

**Comment by luchj1125** [comment]
Kimi, please prepare for release

**Comment by KimiQianMin** [comment]
Release has been done. you can close case.

**Comment by luchj1125** [comment]
Thanks all, will proceed to close ticket
